version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./data/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
      image: certbot/certbot:latest
      volumes:
        - ./data/certbot/www/:/var/www/certbot/:rw
        - ./data/certbot/conf/:/etc/letsencrypt/:rw